//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MQTTClientForm.brokerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListOfString", Namespace="http://opcfoundation.org/UA/2008/02/Types.xsd", ItemName="String")]
    [System.SerializableAttribute()]
    public class ListOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListOfUserTokenPolicy", Namespace="http://opcfoundation.org/UA/2008/02/Types.xsd", ItemName="UserTokenPolicy")]
    [System.SerializableAttribute()]
    public class ListOfUserTokenPolicy : System.Collections.Generic.List<Opc.Ua.UserTokenPolicy> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListOfXmlElement", Namespace="http://opcfoundation.org/UA/2008/02/Types.xsd", ItemName="XmlElement")]
    [System.SerializableAttribute()]
    public class ListOfXmlElement : System.Collections.Generic.List<System.Xml.XmlElement> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListOfCertificateIdentifier", Namespace="http://opcfoundation.org/UA/SDK/Configuration.xsd", ItemName="CertificateIdentifier")]
    [System.SerializableAttribute()]
    public class ListOfCertificateIdentifier : System.Collections.Generic.List<Opc.Ua.CertificateIdentifier> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListOfTransportConfiguration", Namespace="http://opcfoundation.org/UA/SDK/Configuration.xsd", ItemName="TransportConfiguration")]
    [System.SerializableAttribute()]
    public class ListOfTransportConfiguration : System.Collections.Generic.List<Opc.Ua.TransportConfiguration> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListOfServerSecurityPolicy", Namespace="http://opcfoundation.org/UA/SDK/Configuration.xsd", ItemName="ServerSecurityPolicy")]
    [System.SerializableAttribute()]
    public class ListOfServerSecurityPolicy : System.Collections.Generic.List<Opc.Ua.ServerSecurityPolicy> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListOfLocalizedText", Namespace="http://opcfoundation.org/UA/2008/02/Types.xsd", ItemName="LocalizedText")]
    [System.SerializableAttribute()]
    public class ListOfLocalizedText : System.Collections.Generic.List<Opc.Ua.LocalizedText> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListOfServerRegistration", Namespace="http://opcfoundation.org/UA/SDK/Configuration.xsd", ItemName="ServerRegistration")]
    [System.SerializableAttribute()]
    public class ListOfServerRegistration : System.Collections.Generic.List<Opc.Ua.ServerRegistration> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListOfSamplingRateGroup", Namespace="http://opcfoundation.org/UA/SDK/Configuration.xsd", ItemName="SamplingRateGroup")]
    [System.SerializableAttribute()]
    public class ListOfSamplingRateGroup : System.Collections.Generic.List<Opc.Ua.SamplingRateGroup> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListOfEndpointDescription", Namespace="http://opcfoundation.org/UA/2008/02/Types.xsd", ItemName="EndpointDescription")]
    [System.SerializableAttribute()]
    public class ListOfEndpointDescription : System.Collections.Generic.List<Opc.Ua.EndpointDescription> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberInfo", Namespace="http://schemas.datacontract.org/2004/07/System.Reflection")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MQTTClientForm.brokerService.Type))]
    public partial class MemberInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Type", Namespace="http://schemas.datacontract.org/2004/07/System")]
    [System.SerializableAttribute()]
    public partial class Type : MQTTClientForm.brokerService.MemberInfo {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListOfCertificateIdentifier", Namespace="http://opcfoundation.org/UA/2011/03/SecuredApplication.xsd", ItemName="CertificateIdentifier")]
    [System.SerializableAttribute()]
    public class ListOfCertificateIdentifier1 : System.Collections.Generic.List<Opc.Ua.Security.CertificateIdentifier> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListOfBaseAddresses", Namespace="http://opcfoundation.org/UA/2011/03/SecuredApplication.xsd", ItemName="BaseAddress")]
    [System.SerializableAttribute()]
    public class ListOfBaseAddresses : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListOfSecurityProfiles", Namespace="http://opcfoundation.org/UA/2011/03/SecuredApplication.xsd", ItemName="SecurityProfile")]
    [System.SerializableAttribute()]
    public class ListOfSecurityProfiles : System.Collections.Generic.List<Opc.Ua.Security.SecurityProfile> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListOfExtensions", Namespace="http://opcfoundation.org/UA/2011/03/SecuredApplication.xsd", ItemName="Extension")]
    [System.SerializableAttribute()]
    public class ListOfExtensions : System.Collections.Generic.List<System.Xml.XmlElement> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListOfApplicationAccessRule", Namespace="http://opcfoundation.org/UA/SDK/Configuration.xsd", ItemName="ApplicationAccessRule")]
    [System.SerializableAttribute()]
    public class ListOfApplicationAccessRule : System.Collections.Generic.List<Opc.Ua.ApplicationAccessRule> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListOfSimpleAttributeOperand", Namespace="http://opcfoundation.org/UA/2008/02/Types.xsd", ItemName="SimpleAttributeOperand")]
    [System.SerializableAttribute()]
    public class ListOfSimpleAttributeOperand : System.Collections.Generic.List<Opc.Ua.SimpleAttributeOperand> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListOfQualifiedName", Namespace="http://opcfoundation.org/UA/2008/02/Types.xsd", ItemName="QualifiedName")]
    [System.SerializableAttribute()]
    public class ListOfQualifiedName : System.Collections.Generic.List<Opc.Ua.QualifiedName> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListOfContentFilterElement", Namespace="http://opcfoundation.org/UA/2008/02/Types.xsd", ItemName="ContentFilterElement")]
    [System.SerializableAttribute()]
    public class ListOfContentFilterElement : System.Collections.Generic.List<Opc.Ua.ContentFilterElement> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListOfExtensionObject", Namespace="http://opcfoundation.org/UA/2008/02/Types.xsd", ItemName="ExtensionObject")]
    [System.SerializableAttribute()]
    public class ListOfExtensionObject : System.Collections.Generic.List<Opc.Ua.ExtensionObject> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="brokerService.IBrokerService")]
    public interface IBrokerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/MQTTCreateClientAsync", ReplyAction="http://tempuri.org/IBrokerService/MQTTCreateClientAsyncResponse")]
        void MQTTCreateClientAsync(string mqttIP, int option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/MQTTCreateClientAsync", ReplyAction="http://tempuri.org/IBrokerService/MQTTCreateClientAsyncResponse")]
        System.Threading.Tasks.Task MQTTCreateClientAsyncAsync(string mqttIP, int option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/MQTTConnectClientAsync", ReplyAction="http://tempuri.org/IBrokerService/MQTTConnectClientAsyncResponse")]
        void MQTTConnectClientAsync(string mqttIP, int option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/MQTTConnectClientAsync", ReplyAction="http://tempuri.org/IBrokerService/MQTTConnectClientAsyncResponse")]
        System.Threading.Tasks.Task MQTTConnectClientAsyncAsync(string mqttIP, int option);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/MQTTSubscribeTopic", ReplyAction="http://tempuri.org/IBrokerService/MQTTSubscribeTopicResponse")]
        void MQTTSubscribeTopic(string topic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/MQTTSubscribeTopic", ReplyAction="http://tempuri.org/IBrokerService/MQTTSubscribeTopicResponse")]
        System.Threading.Tasks.Task MQTTSubscribeTopicAsync(string topic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/MQTTUnsubscribeTopic", ReplyAction="http://tempuri.org/IBrokerService/MQTTUnsubscribeTopicResponse")]
        void MQTTUnsubscribeTopic(string topic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/MQTTUnsubscribeTopic", ReplyAction="http://tempuri.org/IBrokerService/MQTTUnsubscribeTopicResponse")]
        System.Threading.Tasks.Task MQTTUnsubscribeTopicAsync(string topic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/MQTTPublishTopicAsync", ReplyAction="http://tempuri.org/IBrokerService/MQTTPublishTopicAsyncResponse")]
        void MQTTPublishTopicAsync(string topic, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/MQTTPublishTopicAsync", ReplyAction="http://tempuri.org/IBrokerService/MQTTPublishTopicAsyncResponse")]
        System.Threading.Tasks.Task MQTTPublishTopicAsyncAsync(string topic, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/OPCCreateClient", ReplyAction="http://tempuri.org/IBrokerService/OPCCreateClientResponse")]
        void OPCCreateClient(string opcIP, bool securityCheck);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/OPCCreateClient", ReplyAction="http://tempuri.org/IBrokerService/OPCCreateClientResponse")]
        System.Threading.Tasks.Task OPCCreateClientAsync(string opcIP, bool securityCheck);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/OPCConnectClient", ReplyAction="http://tempuri.org/IBrokerService/OPCConnectClientResponse")]
        void OPCConnectClient();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/OPCConnectClient", ReplyAction="http://tempuri.org/IBrokerService/OPCConnectClientResponse")]
        System.Threading.Tasks.Task OPCConnectClientAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/OPCSubscribeTopic", ReplyAction="http://tempuri.org/IBrokerService/OPCSubscribeTopicResponse")]
        void OPCSubscribeTopic();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/OPCSubscribeTopic", ReplyAction="http://tempuri.org/IBrokerService/OPCSubscribeTopicResponse")]
        System.Threading.Tasks.Task OPCSubscribeTopicAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/OPCUnsubscribeTopic", ReplyAction="http://tempuri.org/IBrokerService/OPCUnsubscribeTopicResponse")]
        void OPCUnsubscribeTopic();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/OPCUnsubscribeTopic", ReplyAction="http://tempuri.org/IBrokerService/OPCUnsubscribeTopicResponse")]
        System.Threading.Tasks.Task OPCUnsubscribeTopicAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/Connect", ReplyAction="http://tempuri.org/IBrokerService/ConnectResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.UserNameIdentityToken))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.X509IdentityToken))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.IssuedIdentityToken))]
        void Connect(Opc.Ua.ConfiguredEndpoint endpoint);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/Connect", ReplyAction="http://tempuri.org/IBrokerService/ConnectResponse")]
        System.Threading.Tasks.Task ConnectAsync(Opc.Ua.ConfiguredEndpoint endpoint);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/GetApplicationInstance", ReplyAction="http://tempuri.org/IBrokerService/GetApplicationInstanceResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.CertificateTrustList))]
        Opc.Ua.Configuration.ApplicationInstance GetApplicationInstance();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/GetApplicationInstance", ReplyAction="http://tempuri.org/IBrokerService/GetApplicationInstanceResponse")]
        System.Threading.Tasks.Task<Opc.Ua.Configuration.ApplicationInstance> GetApplicationInstanceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/GetEndpoints", ReplyAction="http://tempuri.org/IBrokerService/GetEndpointsResponse")]
        Opc.Ua.ConfiguredEndpointCollection GetEndpoints();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/GetEndpoints", ReplyAction="http://tempuri.org/IBrokerService/GetEndpointsResponse")]
        System.Threading.Tasks.Task<Opc.Ua.ConfiguredEndpointCollection> GetEndpointsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/GetSession", ReplyAction="http://tempuri.org/IBrokerService/GetSessionResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.UserNameIdentityToken))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.X509IdentityToken))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.IssuedIdentityToken))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.DataChangeFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.EventFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.AggregateFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.EndpointDescription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ApplicationDescription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.LocalizedText))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ApplicationType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfString))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.MessageSecurityMode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfUserTokenPolicy))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.UserTokenPolicy))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.UserTokenType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.EndpointConfiguration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.UserIdentityToken))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Uuid))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfXmlElement))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfEndpointDescription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfLocalizedText))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.EncodeableFactory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.NamespaceTable))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.StringTable))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.NodeId))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Client.Subscription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.TimestampsToReturn))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Client.MonitoredItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.NodeClass))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.QualifiedName))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.MonitoringMode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.MonitoringFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.DataChangeTrigger))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfSimpleAttributeOperand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.SimpleAttributeOperand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.FilterOperand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfQualifiedName))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ContentFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfContentFilterElement))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ContentFilterElement))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.FilterOperator))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfExtensionObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ExtensionObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.AggregateConfiguration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Client.MonitoredItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Client.Subscription[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Client.Browser))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ViewDescription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.BrowseDirection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.Type))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Configuration.InstalledApplication))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Configuration.StartMode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ConfiguredEndpoint))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.BinaryEncodingSupport))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.EndpointComIdentity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ComSpecification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ApplicationConfiguration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.SecurityConfiguration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.CertificateIdentifier))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.CertificateTrustList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.CertificateStoreIdentifier))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfCertificateIdentifier))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfTransportConfiguration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.TransportConfiguration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.TransportQuotas))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ServerConfiguration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ServerBaseConfiguration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfServerSecurityPolicy))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ServerSecurityPolicy))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfSamplingRateGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.SamplingRateGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ClientConfiguration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.DiscoveryServerConfiguration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfServerRegistration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ServerRegistration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.TraceConfiguration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfApplicationAccessRule))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ApplicationAccessRule))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.AccessControlType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ApplicationAccessRight))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ConfiguredEndpointCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ConfiguredEndpoint[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.MemberInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.SessionClient))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ClientBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ServiceMessageContext))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.DiagnosticsMasks))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Client.NodeCache))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Configuration.ApplicationInstance))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Security.SecuredApplication))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Security.ApplicationType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Security.CertificateIdentifier))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Security.CertificateStoreIdentifier))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Security.CertificateList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfCertificateIdentifier1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfBaseAddresses))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfSecurityProfiles))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Security.SecurityProfile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfExtensions))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.FilterContext))]
        Opc.Ua.Client.Session GetSession();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/GetSession", ReplyAction="http://tempuri.org/IBrokerService/GetSessionResponse")]
        System.Threading.Tasks.Task<Opc.Ua.Client.Session> GetSessionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/GetBrowser", ReplyAction="http://tempuri.org/IBrokerService/GetBrowserResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.UserNameIdentityToken))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.X509IdentityToken))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.IssuedIdentityToken))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.DataChangeFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.EventFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.AggregateFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.EndpointDescription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ApplicationDescription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.LocalizedText))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ApplicationType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfString))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.MessageSecurityMode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfUserTokenPolicy))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.UserTokenPolicy))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.UserTokenType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.EndpointConfiguration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.UserIdentityToken))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Uuid))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfXmlElement))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfEndpointDescription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfLocalizedText))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.EncodeableFactory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.NamespaceTable))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.StringTable))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.NodeId))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Client.Subscription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.TimestampsToReturn))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Client.MonitoredItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.NodeClass))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.QualifiedName))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.MonitoringMode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.MonitoringFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.DataChangeTrigger))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfSimpleAttributeOperand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.SimpleAttributeOperand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.FilterOperand))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfQualifiedName))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ContentFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfContentFilterElement))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ContentFilterElement))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.FilterOperator))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfExtensionObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ExtensionObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.AggregateConfiguration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Client.MonitoredItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Client.Subscription[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ViewDescription))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.BrowseDirection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.Type))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Configuration.InstalledApplication))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Configuration.StartMode))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ConfiguredEndpoint))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.BinaryEncodingSupport))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.EndpointComIdentity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ComSpecification))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ApplicationConfiguration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.SecurityConfiguration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.CertificateIdentifier))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.CertificateTrustList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.CertificateStoreIdentifier))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfCertificateIdentifier))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfTransportConfiguration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.TransportConfiguration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.TransportQuotas))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ServerConfiguration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ServerBaseConfiguration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfServerSecurityPolicy))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ServerSecurityPolicy))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfSamplingRateGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.SamplingRateGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ClientConfiguration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.DiscoveryServerConfiguration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfServerRegistration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ServerRegistration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.TraceConfiguration))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfApplicationAccessRule))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ApplicationAccessRule))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.AccessControlType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ApplicationAccessRight))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ConfiguredEndpointCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ConfiguredEndpoint[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.MemberInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.SessionClient))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ClientBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.ServiceMessageContext))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.DiagnosticsMasks))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Client.NodeCache))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Configuration.ApplicationInstance))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Security.SecuredApplication))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Security.ApplicationType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Security.CertificateIdentifier))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Security.CertificateStoreIdentifier))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Security.CertificateList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfCertificateIdentifier1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfBaseAddresses))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfSecurityProfiles))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.Security.SecurityProfile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MQTTClientForm.brokerService.ListOfExtensions))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Opc.Ua.FilterContext))]
        Opc.Ua.Client.Browser GetBrowser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrokerService/GetBrowser", ReplyAction="http://tempuri.org/IBrokerService/GetBrowserResponse")]
        System.Threading.Tasks.Task<Opc.Ua.Client.Browser> GetBrowserAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBrokerServiceChannel : MQTTClientForm.brokerService.IBrokerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BrokerServiceClient : System.ServiceModel.ClientBase<MQTTClientForm.brokerService.IBrokerService>, MQTTClientForm.brokerService.IBrokerService {
        
        public BrokerServiceClient() {
        }
        
        public BrokerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BrokerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrokerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrokerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void MQTTCreateClientAsync(string mqttIP, int option) {
            base.Channel.MQTTCreateClientAsync(mqttIP, option);
        }
        
        public System.Threading.Tasks.Task MQTTCreateClientAsyncAsync(string mqttIP, int option) {
            return base.Channel.MQTTCreateClientAsyncAsync(mqttIP, option);
        }
        
        public void MQTTConnectClientAsync(string mqttIP, int option) {
            base.Channel.MQTTConnectClientAsync(mqttIP, option);
        }
        
        public System.Threading.Tasks.Task MQTTConnectClientAsyncAsync(string mqttIP, int option) {
            return base.Channel.MQTTConnectClientAsyncAsync(mqttIP, option);
        }
        
        public void MQTTSubscribeTopic(string topic) {
            base.Channel.MQTTSubscribeTopic(topic);
        }
        
        public System.Threading.Tasks.Task MQTTSubscribeTopicAsync(string topic) {
            return base.Channel.MQTTSubscribeTopicAsync(topic);
        }
        
        public void MQTTUnsubscribeTopic(string topic) {
            base.Channel.MQTTUnsubscribeTopic(topic);
        }
        
        public System.Threading.Tasks.Task MQTTUnsubscribeTopicAsync(string topic) {
            return base.Channel.MQTTUnsubscribeTopicAsync(topic);
        }
        
        public void MQTTPublishTopicAsync(string topic, string message) {
            base.Channel.MQTTPublishTopicAsync(topic, message);
        }
        
        public System.Threading.Tasks.Task MQTTPublishTopicAsyncAsync(string topic, string message) {
            return base.Channel.MQTTPublishTopicAsyncAsync(topic, message);
        }
        
        public void OPCCreateClient(string opcIP, bool securityCheck) {
            base.Channel.OPCCreateClient(opcIP, securityCheck);
        }
        
        public System.Threading.Tasks.Task OPCCreateClientAsync(string opcIP, bool securityCheck) {
            return base.Channel.OPCCreateClientAsync(opcIP, securityCheck);
        }
        
        public void OPCConnectClient() {
            base.Channel.OPCConnectClient();
        }
        
        public System.Threading.Tasks.Task OPCConnectClientAsync() {
            return base.Channel.OPCConnectClientAsync();
        }
        
        public void OPCSubscribeTopic() {
            base.Channel.OPCSubscribeTopic();
        }
        
        public System.Threading.Tasks.Task OPCSubscribeTopicAsync() {
            return base.Channel.OPCSubscribeTopicAsync();
        }
        
        public void OPCUnsubscribeTopic() {
            base.Channel.OPCUnsubscribeTopic();
        }
        
        public System.Threading.Tasks.Task OPCUnsubscribeTopicAsync() {
            return base.Channel.OPCUnsubscribeTopicAsync();
        }
        
        public void Connect(Opc.Ua.ConfiguredEndpoint endpoint) {
            base.Channel.Connect(endpoint);
        }
        
        public System.Threading.Tasks.Task ConnectAsync(Opc.Ua.ConfiguredEndpoint endpoint) {
            return base.Channel.ConnectAsync(endpoint);
        }
        
        public Opc.Ua.Configuration.ApplicationInstance GetApplicationInstance() {
            return base.Channel.GetApplicationInstance();
        }
        
        public System.Threading.Tasks.Task<Opc.Ua.Configuration.ApplicationInstance> GetApplicationInstanceAsync() {
            return base.Channel.GetApplicationInstanceAsync();
        }
        
        public Opc.Ua.ConfiguredEndpointCollection GetEndpoints() {
            return base.Channel.GetEndpoints();
        }
        
        public System.Threading.Tasks.Task<Opc.Ua.ConfiguredEndpointCollection> GetEndpointsAsync() {
            return base.Channel.GetEndpointsAsync();
        }
        
        public Opc.Ua.Client.Session GetSession() {
            return base.Channel.GetSession();
        }
        
        public System.Threading.Tasks.Task<Opc.Ua.Client.Session> GetSessionAsync() {
            return base.Channel.GetSessionAsync();
        }
        
        public Opc.Ua.Client.Browser GetBrowser() {
            return base.Channel.GetBrowser();
        }
        
        public System.Threading.Tasks.Task<Opc.Ua.Client.Browser> GetBrowserAsync() {
            return base.Channel.GetBrowserAsync();
        }
    }
}
